; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.5 on Mon Nov 01 2021 18:28:19 GMT+0100 (Mitteleuropäische Normalzeit)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


