; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.5 on Mon Nov 01 2021 18:28:19 GMT+0100 (Mitteleuropäische Normalzeit)
M280 P0 S90 ; retract BLTouch

