; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.5 on Mon Nov 01 2021 18:28:19 GMT+0100 (Mitteleuropäische Normalzeit)

